"""Генерирует файлы piece_renders.c и piece_renders.h.
Каждый спрайт размером 24x24, 2 бита на пиксель, => 144 байта на спрайт (пожалуйста сжатие спаси меня :>).

Почему переменные разделены на два файла и нельзя все написать в .h? (.c - исполняемый, .h - библиотечный файл)
Потому что так компилятору легче понимать, что надо перекомпилировать, а что нет. Почему, хз. Какой-то продвинутый трюк.
"""
# editable constants
BYTES_PER_ELEM = 4
CTYPE = "unsigned long"

# dont touch
PIXELS_PER_ELEM = BYTES_PER_ELEM*4
ELEMS = 24*24*2//8//BYTES_PER_ELEM

piece_names = []

from PIL import Image
import os
with open(os.path.dirname(__file__)+"/piece_renders.c","w") as f:
  f.write("/* This file is autogenerated by create_renders.py */\n")
  for i in os.listdir(os.path.dirname(__file__)+"/pieces"):
    piece_names.append(os.path.basename(i).split(".",1)[0])
    data = [0]*ELEMS
    im = Image.open(os.path.dirname(__file__)+"/pieces/"+i)
    c=0
    for r,g,b,a in im.get_flattened_data(): 
      assert not a or r==g==b, "Pixels must be black, white or transparent"
      # print(c)
      data[c//PIXELS_PER_ELEM]=(data[c//PIXELS_PER_ELEM]<<2) | ((a>0)<<1) | (r>0)
      c+=1
    f.write(f"const {CTYPE} {piece_names[-1]}[{ELEMS}] = ""{" f"{", ".join([hex(i) for i in data])}" "};\n")

  f.write(f"const {CTYPE} *pieces[{len(piece_names)}] = ""{" f"{", ".join(piece_names)}" "};\n")
  
with open(os.path.dirname(__file__)+"/piece_renders.h","w") as f:
  f.write("/* This file is autogenerated by create_renders.py */\n")
  f.write(f"#define SPRITE_TYPE {CTYPE}\n")
  f.write(f"#define SPRITE_ELEMS {ELEMS}\n")
  for i in piece_names: f.write(f"extern const {CTYPE} {i}[{ELEMS}];\n")
  f.write(f"extern const {CTYPE} *pieces[{len(piece_names)}];")