/* This file is autogenerated by create_renders.py */
#define SPRITE_TYPE unsigned long
#define SPRITE_ELEMS 36
extern const unsigned long bishop[36];
extern const unsigned long king[36];
extern const unsigned long knight[36];
extern const unsigned long pawn[36];
extern const unsigned long queen[36];
extern const unsigned long rook[36];
extern const unsigned long *pieces[6];